server:
  port: 8090
  servlet:
    context-path:     

spring:
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 100MB

  mail:
    username: 1539690306@qq.com
    password: vzdporeijqbeggfc
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
##         ssl:
##           enable :true
    default-encoding: utf-8      
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false


  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/association?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
   #redis服务器配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:  
 
 #在控制台显示sql语句 
logging:
  level:
    com.ls.dao.*: debug   
    
mybatis:
  type-aliases-package: com.ls.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
 
mybatis-plus:
  type-aliases-package: com.ls.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
debug: true    
    
